name: EarthSkyLab
favicon: null
layout_spectrum: 0.5274211659561843
typography_spectrum: 0.747996537014842
title: skylab.earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61706352-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0923027298413217
  lightness: 0.8140518076252192
  saturation: 0.9994384131859988
  rhythmicContrast: 0.9104865393601358
purpose: []
