name: SkyLab.Earth
favicon: null
layout_spectrum: 0.26277
typography_spectrum: 0.68941
title: SkyLab.Earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61706352-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#73628c'
    - '#6b2063'
    - '#0c4965'
    - '#c7cbd7'
  brandStrength: 0.0923027298413217
  lightness: 0.875
  saturation: 0.9994384131859988
  rhythmicContrast: 0.75
purpose: []
